kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: samuelph/connectivity-check
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD